export interface Theme {
  id: string;
  name: string;
  styleType: 'solid' | 'gradient';
  category: string;
  badge: string;
  primarySwatch: string;
  secondarySwatch: string;
  bgSwatch: string;
  colors: {
    primary: string;
    secondary: string;
    border: string;
    accent: string;
    accentHover: string;
    orange: string;
    orangeLight: string;
    purple: string;
    purpleLight: string;
    gradientStart: string;
    gradientEnd: string;
    bg: string;
    bgAlt: string;
    dark: string;
    darkCard: string;
  };
}

export const THEMES: Theme[] = [
  // ==========================================
  // SIMPLE & SOLID SINGLE-COLOR PALETTES (NO GRADIENTS)
  // ==========================================
  {
    id: 'solid-navy',
    name: 'Solid Classic Navy',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Navy',
    primarySwatch: '#1D4ED8',
    secondarySwatch: '#1D4ED8',
    bgSwatch: '#F8FAFC',
    colors: {
      primary: '#0F172A',
      secondary: '#475569',
      border: '#E2E8F0',
      accent: '#1D4ED8',
      accentHover: '#1E40AF',
      orange: '#1D4ED8',
      orangeLight: '#3B82F6',
      purple: '#1D4ED8',
      purpleLight: '#3B82F6',
      gradientStart: '#1D4ED8',
      gradientEnd: '#1D4ED8',
      bg: '#F8FAFC',
      bgAlt: '#F1F5F9',
      dark: '#0A1128',
      darkCard: '#101B3B',
    },
  },
  {
    id: 'solid-brand-purple',
    name: 'Solid Signature Purple',
    styleType: 'solid',
    category: 'Original Brand Solid',
    badge: 'Original Purple',
    primarySwatch: '#7026ED',
    secondarySwatch: '#7026ED',
    bgSwatch: '#FAF8FD',
    colors: {
      primary: '#1A1028',
      secondary: '#5A4E6D',
      border: '#EAE5F5',
      accent: '#7026ED',
      accentHover: '#5B1EC7',
      orange: '#7026ED',
      orangeLight: '#9B51E0',
      purple: '#7026ED',
      purpleLight: '#9B51E0',
      gradientStart: '#7026ED',
      gradientEnd: '#7026ED',
      bg: '#FFFFFF',
      bgAlt: '#FAF8FD',
      dark: '#120824',
      darkCard: '#1C1035',
    },
  },
  {
    id: 'solid-brand-orange',
    name: 'Solid Vibrant Orange',
    styleType: 'solid',
    category: 'Original Brand Solid',
    badge: 'Original Orange',
    primarySwatch: '#ED6C26',
    secondarySwatch: '#ED6C26',
    bgSwatch: '#FFFBF7',
    colors: {
      primary: '#1C1008',
      secondary: '#5C4E46',
      border: '#FCE7D8',
      accent: '#ED6C26',
      accentHover: '#C85215',
      orange: '#ED6C26',
      orangeLight: '#F2994A',
      purple: '#ED6C26',
      purpleLight: '#F2994A',
      gradientStart: '#ED6C26',
      gradientEnd: '#ED6C26',
      bg: '#FFFBF7',
      bgAlt: '#FDF4EC',
      dark: '#1A0C04',
      darkCard: '#2B1408',
    },
  },
  {
    id: 'solid-blue',
    name: 'Solid Royal Cobalt',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Cobalt',
    primarySwatch: '#2563EB',
    secondarySwatch: '#2563EB',
    bgSwatch: '#F8FAFC',
    colors: {
      primary: '#0F172A',
      secondary: '#475569',
      border: '#E2E8F0',
      accent: '#2563EB',
      accentHover: '#1D4ED8',
      orange: '#2563EB',
      orangeLight: '#60A5FA',
      purple: '#2563EB',
      purpleLight: '#60A5FA',
      gradientStart: '#2563EB',
      gradientEnd: '#2563EB',
      bg: '#F8FAFC',
      bgAlt: '#F1F5F9',
      dark: '#09132A',
      darkCard: '#102046',
    },
  },
  {
    id: 'solid-sky',
    name: 'Solid Sky Blue',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Sky Blue',
    primarySwatch: '#0284C7',
    secondarySwatch: '#0284C7',
    bgSwatch: '#F0F9FF',
    colors: {
      primary: '#0F172A',
      secondary: '#475569',
      border: '#E0F2FE',
      accent: '#0284C7',
      accentHover: '#0369A1',
      orange: '#0284C7',
      orangeLight: '#38BDF8',
      purple: '#0284C7',
      purpleLight: '#38BDF8',
      gradientStart: '#0284C7',
      gradientEnd: '#0284C7',
      bg: '#F8FAFC',
      bgAlt: '#F0F9FF',
      dark: '#082F49',
      darkCard: '#0C3A5E',
    },
  },
  {
    id: 'solid-indigo',
    name: 'Solid Corporate Indigo',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Indigo',
    primarySwatch: '#4338CA',
    secondarySwatch: '#4338CA',
    bgSwatch: '#F5F3FF',
    colors: {
      primary: '#0F172A',
      secondary: '#475569',
      border: '#E0E7FF',
      accent: '#4338CA',
      accentHover: '#3730A3',
      orange: '#4338CA',
      orangeLight: '#6366F1',
      purple: '#4338CA',
      purpleLight: '#6366F1',
      gradientStart: '#4338CA',
      gradientEnd: '#4338CA',
      bg: '#F8FAFC',
      bgAlt: '#EEF2FF',
      dark: '#0B0F2A',
      darkCard: '#151B42',
    },
  },
  {
    id: 'solid-teal',
    name: 'Solid Deep Teal',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Deep Teal',
    primarySwatch: '#0F766E',
    secondarySwatch: '#0F766E',
    bgSwatch: '#F8FAFB',
    colors: {
      primary: '#081D1B',
      secondary: '#475569',
      border: '#E2EFEF',
      accent: '#0F766E',
      accentHover: '#115E59',
      orange: '#0F766E',
      orangeLight: '#14B8A6',
      purple: '#0F766E',
      purpleLight: '#14B8A6',
      gradientStart: '#0F766E',
      gradientEnd: '#0F766E',
      bg: '#F8FAFB',
      bgAlt: '#ECF5F5',
      dark: '#041615',
      darkCard: '#092523',
    },
  },
  {
    id: 'solid-cyan',
    name: 'Solid Modern Cyan',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Cyan',
    primarySwatch: '#0891B2',
    secondarySwatch: '#0891B2',
    bgSwatch: '#F0FDFA',
    colors: {
      primary: '#06202A',
      secondary: '#475569',
      border: '#CFFAFE',
      accent: '#0891B2',
      accentHover: '#0E7490',
      orange: '#0891B2',
      orangeLight: '#22D3EE',
      purple: '#0891B2',
      purpleLight: '#22D3EE',
      gradientStart: '#0891B2',
      gradientEnd: '#0891B2',
      bg: '#F8FAFC',
      bgAlt: '#ECFEFF',
      dark: '#041B24',
      darkCard: '#082E3D',
    },
  },
  {
    id: 'solid-forest',
    name: 'Solid Forest Green',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Forest Green',
    primarySwatch: '#15803D',
    secondarySwatch: '#15803D',
    bgSwatch: '#F8FAF8',
    colors: {
      primary: '#091B0F',
      secondary: '#475569',
      border: '#E3ECE5',
      accent: '#15803D',
      accentHover: '#166534',
      orange: '#15803D',
      orangeLight: '#22C55E',
      purple: '#15803D',
      purpleLight: '#22C55E',
      gradientStart: '#15803D',
      gradientEnd: '#15803D',
      bg: '#F8FAF8',
      bgAlt: '#EEF5EF',
      dark: '#05140A',
      darkCard: '#0C2414',
    },
  },
  {
    id: 'solid-emerald',
    name: 'Solid Emerald Green',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Emerald',
    primarySwatch: '#059669',
    secondarySwatch: '#059669',
    bgSwatch: '#F0FDF4',
    colors: {
      primary: '#062014',
      secondary: '#475569',
      border: '#D1FAE5',
      accent: '#059669',
      accentHover: '#047857',
      orange: '#059669',
      orangeLight: '#34D399',
      purple: '#059669',
      purpleLight: '#34D399',
      gradientStart: '#059669',
      gradientEnd: '#059669',
      bg: '#F8FAF8',
      bgAlt: '#ECFDF5',
      dark: '#03180F',
      darkCard: '#082B1B',
    },
  },
  {
    id: 'solid-olive',
    name: 'Solid Nordic Olive',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Olive',
    primarySwatch: '#3F6212',
    secondarySwatch: '#3F6212',
    bgSwatch: '#F7FEE7',
    colors: {
      primary: '#141E08',
      secondary: '#475569',
      border: '#ECFCCB',
      accent: '#3F6212',
      accentHover: '#365314',
      orange: '#3F6212',
      orangeLight: '#65A30D',
      purple: '#3F6212',
      purpleLight: '#65A30D',
      gradientStart: '#3F6212',
      gradientEnd: '#3F6212',
      bg: '#F8FAF8',
      bgAlt: '#F4F9EC',
      dark: '#0E1705',
      darkCard: '#1A280B',
    },
  },
  {
    id: 'solid-crimson',
    name: 'Solid Crimson Wine',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Crimson',
    primarySwatch: '#BE123C',
    secondarySwatch: '#BE123C',
    bgSwatch: '#FFFBFB',
    colors: {
      primary: '#1F0B10',
      secondary: '#664F54',
      border: '#F6E6E9',
      accent: '#BE123C',
      accentHover: '#9F1239',
      orange: '#BE123C',
      orangeLight: '#F43F5E',
      purple: '#BE123C',
      purpleLight: '#F43F5E',
      gradientStart: '#BE123C',
      gradientEnd: '#BE123C',
      bg: '#FFFBFB',
      bgAlt: '#F9ECEE',
      dark: '#140609',
      darkCard: '#240C12',
    },
  },
  {
    id: 'solid-burgundy',
    name: 'Solid Deep Burgundy',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Burgundy',
    primarySwatch: '#881337',
    secondarySwatch: '#881337',
    bgSwatch: '#FFF1F2',
    colors: {
      primary: '#1F070E',
      secondary: '#5C444B',
      border: '#FFE4E6',
      accent: '#881337',
      accentHover: '#700F2B',
      orange: '#881337',
      orangeLight: '#E11D48',
      purple: '#881337',
      purpleLight: '#E11D48',
      gradientStart: '#881337',
      gradientEnd: '#881337',
      bg: '#FFFBFB',
      bgAlt: '#FFF1F2',
      dark: '#140409',
      darkCard: '#240A12',
    },
  },
  {
    id: 'solid-terracotta',
    name: 'Solid Warm Terracotta',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Terracotta',
    primarySwatch: '#C2410C',
    secondarySwatch: '#C2410C',
    bgSwatch: '#FFF7ED',
    colors: {
      primary: '#1F1008',
      secondary: '#5C4E46',
      border: '#FFEDD5',
      accent: '#C2410C',
      accentHover: '#9A3412',
      orange: '#C2410C',
      orangeLight: '#FB923C',
      purple: '#C2410C',
      purpleLight: '#FB923C',
      gradientStart: '#C2410C',
      gradientEnd: '#C2410C',
      bg: '#FFFBF8',
      bgAlt: '#FFF7ED',
      dark: '#170B04',
      darkCard: '#2A1509',
    },
  },
  {
    id: 'solid-camel',
    name: 'Solid Warm Camel',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Camel',
    primarySwatch: '#B45309',
    secondarySwatch: '#B45309',
    bgSwatch: '#FCFAF7',
    colors: {
      primary: '#1E1408',
      secondary: '#695745',
      border: '#EFE7DE',
      accent: '#B45309',
      accentHover: '#92400E',
      orange: '#B45309',
      orangeLight: '#F59E0B',
      purple: '#B45309',
      purpleLight: '#F59E0B',
      gradientStart: '#B45309',
      gradientEnd: '#B45309',
      bg: '#FCFAF7',
      bgAlt: '#F4ECE2',
      dark: '#140C04',
      darkCard: '#231608',
    },
  },
  {
    id: 'solid-amber',
    name: 'Solid Amber Gold',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Amber',
    primarySwatch: '#D97706',
    secondarySwatch: '#D97706',
    bgSwatch: '#FFFBEB',
    colors: {
      primary: '#1F1608',
      secondary: '#5C5144',
      border: '#FEF3C7',
      accent: '#D97706',
      accentHover: '#B45309',
      orange: '#D97706',
      orangeLight: '#FBBF24',
      purple: '#D97706',
      purpleLight: '#FBBF24',
      gradientStart: '#D97706',
      gradientEnd: '#D97706',
      bg: '#FFFCF5',
      bgAlt: '#FEF8E7',
      dark: '#140E04',
      darkCard: '#241B08',
    },
  },
  {
    id: 'solid-espresso',
    name: 'Solid Espresso Walnut',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Espresso',
    primarySwatch: '#78350F',
    secondarySwatch: '#78350F',
    bgSwatch: '#FAF7F4',
    colors: {
      primary: '#1A0E06',
      secondary: '#5C4E46',
      border: '#EBE2D8',
      accent: '#78350F',
      accentHover: '#59260A',
      orange: '#78350F',
      orangeLight: '#A14D1A',
      purple: '#78350F',
      purpleLight: '#A14D1A',
      gradientStart: '#78350F',
      gradientEnd: '#78350F',
      bg: '#FAF7F4',
      bgAlt: '#F2E9DF',
      dark: '#120904',
      darkCard: '#211208',
    },
  },
  {
    id: 'solid-charcoal',
    name: 'Solid Steel Charcoal',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Charcoal',
    primarySwatch: '#374151',
    secondarySwatch: '#374151',
    bgSwatch: '#F9FAFB',
    colors: {
      primary: '#111827',
      secondary: '#4B5563',
      border: '#E5E7EB',
      accent: '#374151',
      accentHover: '#1F2937',
      orange: '#374151',
      orangeLight: '#6B7280',
      purple: '#374151',
      purpleLight: '#6B7280',
      gradientStart: '#374151',
      gradientEnd: '#374151',
      bg: '#F9FAFB',
      bgAlt: '#F3F4F6',
      dark: '#0B0F19',
      darkCard: '#171E2E',
    },
  },
  {
    id: 'solid-black',
    name: 'Solid Obsidian Black',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Obsidian',
    primarySwatch: '#18181B',
    secondarySwatch: '#18181B',
    bgSwatch: '#FAFAFA',
    colors: {
      primary: '#09090B',
      secondary: '#52525B',
      border: '#E4E4E7',
      accent: '#18181B',
      accentHover: '#27272A',
      orange: '#18181B',
      orangeLight: '#71717A',
      purple: '#18181B',
      purpleLight: '#71717A',
      gradientStart: '#18181B',
      gradientEnd: '#18181B',
      bg: '#FAFAFA',
      bgAlt: '#F4F4F5',
      dark: '#09090B',
      darkCard: '#18181B',
    },
  },
  {
    id: 'solid-violet',
    name: 'Solid Royal Violet',
    styleType: 'solid',
    category: 'Pure Single Color',
    badge: 'Violet',
    primarySwatch: '#6D28D9',
    secondarySwatch: '#6D28D9',
    bgSwatch: '#FAF7FD',
    colors: {
      primary: '#140924',
      secondary: '#524761',
      border: '#EDE5F7',
      accent: '#6D28D9',
      accentHover: '#5B21B6',
      orange: '#6D28D9',
      orangeLight: '#8B5CF6',
      purple: '#6D28D9',
      purpleLight: '#8B5CF6',
      gradientStart: '#6D28D9',
      gradientEnd: '#6D28D9',
      bg: '#FAF7FD',
      bgAlt: '#F3ECFA',
      dark: '#10061E',
      darkCard: '#1D0E36',
    },
  },
  {
    id: 'solid-coral',
    name: 'Solid Radiant Coral',
    styleType: 'solid',
    category: 'Vibrant Modern Energy',
    badge: 'Coral',
    primarySwatch: '#F43F5E',
    secondarySwatch: '#F43F5E',
    bgSwatch: '#FFFBFB',
    colors: {
      primary: '#1C0B12',
      secondary: '#614B53',
      border: '#FFE4E8',
      accent: '#F43F5E',
      accentHover: '#E11D48',
      orange: '#F43F5E',
      orangeLight: '#FB7185',
      purple: '#F43F5E',
      purpleLight: '#FB7185',
      gradientStart: '#F43F5E',
      gradientEnd: '#F43F5E',
      bg: '#FFFBFB',
      bgAlt: '#FFF1F3',
      dark: '#16040C',
      darkCard: '#260816',
    },
  },
  {
    id: 'solid-mulberry',
    name: 'Solid Mulberry Plum',
    styleType: 'solid',
    category: 'Prestige Executive Velvet',
    badge: 'Mulberry',
    primarySwatch: '#86198F',
    secondarySwatch: '#86198F',
    bgSwatch: '#FCF9FD',
    colors: {
      primary: '#1A0A1C',
      secondary: '#5E4B60',
      border: '#F5E8F7',
      accent: '#86198F',
      accentHover: '#701A75',
      orange: '#86198F',
      orangeLight: '#A21CAF',
      purple: '#86198F',
      purpleLight: '#A21CAF',
      gradientStart: '#86198F',
      gradientEnd: '#86198F',
      bg: '#FCF9FD',
      bgAlt: '#F8EEFA',
      dark: '#140516',
      darkCard: '#220926',
    },
  },
  {
    id: 'solid-iris',
    name: 'Solid Electric Iris',
    styleType: 'solid',
    category: 'Contemporary Tech & Design',
    badge: 'Iris',
    primarySwatch: '#4F46E5',
    secondarySwatch: '#4F46E5',
    bgSwatch: '#F9FAFE',
    colors: {
      primary: '#0F1126',
      secondary: '#4B4F69',
      border: '#E5E7FA',
      accent: '#4F46E5',
      accentHover: '#4338CA',
      orange: '#4F46E5',
      orangeLight: '#6366F1',
      purple: '#4F46E5',
      purpleLight: '#6366F1',
      gradientStart: '#4F46E5',
      gradientEnd: '#4F46E5',
      bg: '#F9FAFE',
      bgAlt: '#EFF1FC',
      dark: '#0B0D1E',
      darkCard: '#151833',
    },
  },
  {
    id: 'solid-sage',
    name: 'Solid Botanical Sage',
    styleType: 'solid',
    category: 'Calm Earth & Botanicals',
    badge: 'Sage',
    primarySwatch: '#3F7A5C',
    secondarySwatch: '#3F7A5C',
    bgSwatch: '#F8FBF9',
    colors: {
      primary: '#0D1C14',
      secondary: '#4A5E53',
      border: '#DEEDE4',
      accent: '#3F7A5C',
      accentHover: '#2E5E45',
      orange: '#3F7A5C',
      orangeLight: '#529973',
      purple: '#3F7A5C',
      purpleLight: '#529973',
      gradientStart: '#3F7A5C',
      gradientEnd: '#3F7A5C',
      bg: '#F8FBF9',
      bgAlt: '#EEF6F1',
      dark: '#07150E',
      darkCard: '#0E2319',
    },
  },
  {
    id: 'solid-copper',
    name: 'Solid Burnished Copper',
    styleType: 'solid',
    category: 'Refined Metallic Warmth',
    badge: 'Copper',
    primarySwatch: '#C25E00',
    secondarySwatch: '#C25E00',
    bgSwatch: '#FFFBF8',
    colors: {
      primary: '#1F1106',
      secondary: '#615043',
      border: '#FCEBDC',
      accent: '#C25E00',
      accentHover: '#9E4B00',
      orange: '#C25E00',
      orangeLight: '#E07A1E',
      purple: '#C25E00',
      purpleLight: '#E07A1E',
      gradientStart: '#C25E00',
      gradientEnd: '#C25E00',
      bg: '#FFFBF8',
      bgAlt: '#FBF2E9',
      dark: '#170A02',
      darkCard: '#271407',
    },
  },
  {
    id: 'solid-lavender',
    name: 'Solid French Lavender',
    styleType: 'solid',
    category: 'Soft Minimalist Editorial',
    badge: 'Lavender',
    primarySwatch: '#7C3AED',
    secondarySwatch: '#7C3AED',
    bgSwatch: '#FAF8FE',
    colors: {
      primary: '#150C24',
      secondary: '#584B66',
      border: '#EFE8FC',
      accent: '#7C3AED',
      accentHover: '#6D28D9',
      orange: '#7C3AED',
      orangeLight: '#9333EA',
      purple: '#7C3AED',
      purpleLight: '#9333EA',
      gradientStart: '#7C3AED',
      gradientEnd: '#7C3AED',
      bg: '#FAF8FE',
      bgAlt: '#F3EEFB',
      dark: '#10071C',
      darkCard: '#1C0F32',
    },
  },
  {
    id: 'solid-oxford',
    name: 'Solid Midnight Oxford',
    styleType: 'solid',
    category: 'Ivy League Heritage',
    badge: 'Oxford Blue',
    primarySwatch: '#1E3A8A',
    secondarySwatch: '#1E3A8A',
    bgSwatch: '#F8FAFC',
    colors: {
      primary: '#0A1128',
      secondary: '#434F69',
      border: '#DCE4F5',
      accent: '#1E3A8A',
      accentHover: '#172554',
      orange: '#1E3A8A',
      orangeLight: '#2563EB',
      purple: '#1E3A8A',
      purpleLight: '#2563EB',
      gradientStart: '#1E3A8A',
      gradientEnd: '#1E3A8A',
      bg: '#F8FAFC',
      bgAlt: '#EDF3FC',
      dark: '#060B1C',
      darkCard: '#0E1734',
    },
  },
  {
    id: 'solid-honey',
    name: 'Solid Artisan Honey',
    styleType: 'solid',
    category: 'Radiant Artisan Gold',
    badge: 'Honey Gold',
    primarySwatch: '#CA8A04',
    secondarySwatch: '#CA8A04',
    bgSwatch: '#FFFCF2',
    colors: {
      primary: '#1E1805',
      secondary: '#61563F',
      border: '#FEF3C7',
      accent: '#CA8A04',
      accentHover: '#A16207',
      orange: '#CA8A04',
      orangeLight: '#EAB308',
      purple: '#CA8A04',
      purpleLight: '#EAB308',
      gradientStart: '#CA8A04',
      gradientEnd: '#CA8A04',
      bg: '#FFFCF2',
      bgAlt: '#FEF9E3',
      dark: '#141003',
      darkCard: '#241C06',
    },
  },

  // ==========================================
  // DUAL-TONE & GRADIENT PALETTES
  // ==========================================
  {
    id: 'signature-purple-orange',
    name: 'Signature Purple & Vibrant Orange',
    styleType: 'gradient',
    category: 'Original Brand Identity',
    badge: 'Original',
    primarySwatch: '#7026ED',
    secondarySwatch: '#ED6C26',
    bgSwatch: '#FFFFFF',
    colors: {
      primary: '#1A1028',
      secondary: '#5A4E6D',
      border: '#EAE5F5',
      accent: '#7026ED',
      accentHover: '#5B1EC7',
      orange: '#ED6C26',
      orangeLight: '#F2994A',
      purple: '#7026ED',
      purpleLight: '#9B51E0',
      gradientStart: '#7026ED',
      gradientEnd: '#ED6C26',
      bg: '#FFFFFF',
      bgAlt: '#FAF8FD',
      dark: '#120824',
      darkCard: '#1C1035',
    },
  },
  {
    id: 'executive-gold',
    name: 'Executive Navy & Gold',
    styleType: 'gradient',
    category: 'High-Ticket Advisory',
    badge: 'Gold',
    primarySwatch: '#C59B27',
    secondarySwatch: '#0A0F1D',
    bgSwatch: '#FAF9F6',
    colors: {
      primary: '#0A0F1D',
      secondary: '#475569',
      border: '#E8E5DF',
      accent: '#C59B27',
      accentHover: '#A8821B',
      orange: '#D4AF37',
      orangeLight: '#F3E5AB',
      purple: '#C59B27',
      purpleLight: '#E5C365',
      gradientStart: '#B8860B',
      gradientEnd: '#E5C365',
      bg: '#FAF9F6',
      bgAlt: '#F2EFEB',
      dark: '#070B14',
      darkCard: '#0F1626',
    },
  },
  {
    id: 'sapphire-sky',
    name: 'Sapphire & Sky Blue',
    styleType: 'gradient',
    category: 'Silicon Valley AI Tech',
    badge: 'Sky Gradient',
    primarySwatch: '#0284C7',
    secondarySwatch: '#38BDF8',
    bgSwatch: '#F0F9FF',
    colors: {
      primary: '#0F172A',
      secondary: '#475569',
      border: '#E0F2FE',
      accent: '#0284C7',
      accentHover: '#0369A1',
      orange: '#38BDF8',
      orangeLight: '#7DD3FC',
      purple: '#0284C7',
      purpleLight: '#38BDF8',
      gradientStart: '#0284C7',
      gradientEnd: '#38BDF8',
      bg: '#F0F9FF',
      bgAlt: '#E0F2FE',
      dark: '#082F49',
      darkCard: '#0C3A5E',
    },
  },
  {
    id: 'emerald-growth',
    name: 'Emerald & Mint',
    styleType: 'gradient',
    category: 'Organic Growth & Wealth',
    badge: 'Mint Gradient',
    primarySwatch: '#059669',
    secondarySwatch: '#10B981',
    bgSwatch: '#F7FBF9',
    colors: {
      primary: '#061C14',
      secondary: '#475569',
      border: '#E2F0E7',
      accent: '#059669',
      accentHover: '#047857',
      orange: '#10B981',
      orangeLight: '#34D399',
      purple: '#059669',
      purpleLight: '#34D399',
      gradientStart: '#059669',
      gradientEnd: '#10B981',
      bg: '#F7FBF9',
      bgAlt: '#EAF5EF',
      dark: '#04140E',
      darkCard: '#0A2419',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold & Velvet Plum',
    styleType: 'gradient',
    category: 'Chic Feminine Luxury',
    badge: 'Plum Gradient',
    primarySwatch: '#D946EF',
    secondarySwatch: '#FB7185',
    bgSwatch: '#FDF9FA',
    colors: {
      primary: '#1F1427',
      secondary: '#725B78',
      border: '#F0E3EC',
      accent: '#E11D48',
      accentHover: '#BE123C',
      orange: '#FB7185',
      orangeLight: '#FDA4AF',
      purple: '#D946EF',
      purpleLight: '#F0ABFC',
      gradientStart: '#D946EF',
      gradientEnd: '#FB7185',
      bg: '#FDF9FA',
      bgAlt: '#F9EFF3',
      dark: '#160C1B',
      darkCard: '#23152B',
    },
  },
  {
    id: 'terracotta-sunset',
    name: 'Terracotta & Sunset Amber',
    styleType: 'gradient',
    category: 'Mediterranean Warmth',
    badge: 'Sunset',
    primarySwatch: '#EA580C',
    secondarySwatch: '#FB923C',
    bgSwatch: '#FFFBF7',
    colors: {
      primary: '#1C130C',
      secondary: '#6B5B52',
      border: '#F4ECE6',
      accent: '#EA580C',
      accentHover: '#C2410C',
      orange: '#FB923C',
      orangeLight: '#FDBA74',
      purple: '#EA580C',
      purpleLight: '#FB923C',
      gradientStart: '#EA580C',
      gradientEnd: '#FB923C',
      bg: '#FFFBF7',
      bgAlt: '#F8EFE7',
      dark: '#180F08',
      darkCard: '#24160E',
    },
  },
  {
    id: 'royal-amethyst',
    name: 'Royal Amethyst & Violet',
    styleType: 'gradient',
    category: 'Sovereign Luxury & Intellect',
    badge: 'Amethyst',
    primarySwatch: '#7E22CE',
    secondarySwatch: '#A855F7',
    bgSwatch: '#FAF7FD',
    colors: {
      primary: '#150B24',
      secondary: '#5F526F',
      border: '#EFE9F6',
      accent: '#7E22CE',
      accentHover: '#6B21A8',
      orange: '#A855F7',
      orangeLight: '#C084FC',
      purple: '#7E22CE',
      purpleLight: '#A855F7',
      gradientStart: '#7E22CE',
      gradientEnd: '#C084FC',
      bg: '#FAF7FD',
      bgAlt: '#F3EDF9',
      dark: '#11081F',
      darkCard: '#1C0F32',
    },
  },
  {
    id: 'nordic-sage',
    name: 'Nordic Sage & Olive',
    styleType: 'gradient',
    category: 'Scandinavian Organic Calm',
    badge: 'Sage',
    primarySwatch: '#4D7C0F',
    secondarySwatch: '#84CC16',
    bgSwatch: '#F8FAF8',
    colors: {
      primary: '#131E17',
      secondary: '#506155',
      border: '#E3ECE5',
      accent: '#3F6212',
      accentHover: '#365314',
      orange: '#65A30D',
      orangeLight: '#84CC16',
      purple: '#4D7C0F',
      purpleLight: '#65A30D',
      gradientStart: '#3F6212',
      gradientEnd: '#84CC16',
      bg: '#F8FAF8',
      bgAlt: '#EDF2EE',
      dark: '#0C140F',
      darkCard: '#14221A',
    },
  },
  {
    id: 'mocha-espresso',
    name: 'Mocha Latte & Warm Espresso',
    styleType: 'gradient',
    category: 'Editorial Cashmere Warmth',
    badge: 'Mocha',
    primarySwatch: '#78350F',
    secondarySwatch: '#D97706',
    bgSwatch: '#FAF7F4',
    colors: {
      primary: '#1C130D',
      secondary: '#6E5C50',
      border: '#EDE6DF',
      accent: '#78350F',
      accentHover: '#5C2809',
      orange: '#D97706',
      orangeLight: '#FBBF24',
      purple: '#92400E',
      purpleLight: '#D97706',
      gradientStart: '#78350F',
      gradientEnd: '#D97706',
      bg: '#FAF7F4',
      bgAlt: '#F2EAE2',
      dark: '#140C07',
      darkCard: '#1F140D',
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Teal & Aqua Ice',
    styleType: 'gradient',
    category: 'Futuristic Matrix & Search',
    badge: 'Cyber',
    primarySwatch: '#0D9488',
    secondarySwatch: '#06B6D4',
    bgSwatch: '#F0FDFA',
    colors: {
      primary: '#042F2E',
      secondary: '#334155',
      border: '#CCFBF1',
      accent: '#0D9488',
      accentHover: '#0F766E',
      orange: '#06B6D4',
      orangeLight: '#22D3EE',
      purple: '#0D9488',
      purpleLight: '#14B8A6',
      gradientStart: '#0F766E',
      gradientEnd: '#22D3EE',
      bg: '#F0FDFA',
      bgAlt: '#CCFBF1',
      dark: '#021D1D',
      darkCard: '#052B2A',
    },
  },
  {
    id: 'obsidian-slate',
    name: 'Obsidian & Titanium',
    styleType: 'gradient',
    category: 'Minimalist Monochrome',
    badge: 'Monochrome',
    primarySwatch: '#18181B',
    secondarySwatch: '#71717A',
    bgSwatch: '#FAFAFA',
    colors: {
      primary: '#09090B',
      secondary: '#52525B',
      border: '#E4E4E7',
      accent: '#18181B',
      accentHover: '#27272A',
      orange: '#71717A',
      orangeLight: '#A14D1A',
      purple: '#27272A',
      purpleLight: '#52525B',
      gradientStart: '#18181B',
      gradientEnd: '#71717A',
      bg: '#FAFAFA',
      bgAlt: '#F4F4F5',
      dark: '#09090B',
      darkCard: '#18181B',
    },
  },
  {
    id: 'aurora-borealis',
    name: 'Northern Lights Aurora',
    styleType: 'gradient',
    category: 'High-Impact Nordic Glow',
    badge: 'Aurora Borealis',
    primarySwatch: '#0D9488',
    secondarySwatch: '#10B981',
    bgSwatch: '#F5FBFA',
    colors: {
      primary: '#061D1A',
      secondary: '#435854',
      border: '#D1F2EB',
      accent: '#0D9488',
      accentHover: '#0F766E',
      orange: '#10B981',
      orangeLight: '#34D399',
      purple: '#0D9488',
      purpleLight: '#14B8A6',
      gradientStart: '#0D9488',
      gradientEnd: '#10B981',
      bg: '#F5FBFA',
      bgAlt: '#E8F7F3',
      dark: '#041513',
      darkCard: '#0A2421',
    },
  },
  {
    id: 'sunset-peach',
    name: 'Sunset Horizon & Peach',
    styleType: 'gradient',
    category: 'Warm Creative Glow',
    badge: 'Peach Sunset',
    primarySwatch: '#E11D48',
    secondarySwatch: '#F97316',
    bgSwatch: '#FFFBFB',
    colors: {
      primary: '#1E0C10',
      secondary: '#634E52',
      border: '#FDE2E4',
      accent: '#E11D48',
      accentHover: '#BE123C',
      orange: '#F97316',
      orangeLight: '#FB923C',
      purple: '#E11D48',
      purpleLight: '#FB7185',
      gradientStart: '#E11D48',
      gradientEnd: '#F97316',
      bg: '#FFFBFB',
      bgAlt: '#FFF1F2',
      dark: '#17060A',
      darkCard: '#260B12',
    },
  },
  {
    id: 'mediterranean-azure',
    name: 'Deep Azure & Seafoam',
    styleType: 'gradient',
    category: 'Coastal Authority & Clarity',
    badge: 'Deep Azure',
    primarySwatch: '#1D4ED8',
    secondarySwatch: '#06B6D4',
    bgSwatch: '#F7FAFD',
    colors: {
      primary: '#081429',
      secondary: '#40516E',
      border: '#D8E6FA',
      accent: '#1D4ED8',
      accentHover: '#1E40AF',
      orange: '#06B6D4',
      orangeLight: '#38BDF8',
      purple: '#1D4ED8',
      purpleLight: '#60A5FA',
      gradientStart: '#1D4ED8',
      gradientEnd: '#06B6D4',
      bg: '#F7FAFD',
      bgAlt: '#ECF3FC',
      dark: '#050E20',
      darkCard: '#0C1A38',
    },
  },
  {
    id: 'blackberry-orchid',
    name: 'Velvet Blackberry & Orchid',
    styleType: 'gradient',
    category: 'Ultra-Luxe Couture',
    badge: 'Velvet Orchid',
    primarySwatch: '#701A75',
    secondarySwatch: '#C026D3',
    bgSwatch: '#FCF8FD',
    colors: {
      primary: '#1C081E',
      secondary: '#614B63',
      border: '#F6E4F8',
      accent: '#86198F',
      accentHover: '#701A75',
      orange: '#C026D3',
      orangeLight: '#E879F9',
      purple: '#701A75',
      purpleLight: '#A21CAF',
      gradientStart: '#701A75',
      gradientEnd: '#C026D3',
      bg: '#FCF8FD',
      bgAlt: '#F8EDFB',
      dark: '#140416',
      darkCard: '#230727',
    },
  },
  {
    id: 'sedona-copper',
    name: 'Sedona Dunes & Ochre',
    styleType: 'gradient',
    category: 'Architectural Earth & Clay',
    badge: 'Sedona Dunes',
    primarySwatch: '#C2410C',
    secondarySwatch: '#EAB308',
    bgSwatch: '#FFFBF7',
    colors: {
      primary: '#1E1006',
      secondary: '#615042',
      border: '#FBE8D5',
      accent: '#C2410C',
      accentHover: '#9A3412',
      orange: '#EAB308',
      orangeLight: '#FACC15',
      purple: '#C2410C',
      purpleLight: '#FB923C',
      gradientStart: '#C2410C',
      gradientEnd: '#EAB308',
      bg: '#FFFBF7',
      bgAlt: '#FBF2E7',
      dark: '#150A03',
      darkCard: '#241306',
    },
  },
  {
    id: 'electric-flamingo',
    name: 'Electric Flamingo & Indigo',
    styleType: 'gradient',
    category: 'High-Voltage Creative Agency',
    badge: 'Electric Flamingo',
    primarySwatch: '#4F46E5',
    secondarySwatch: '#F43F5E',
    bgSwatch: '#FCF9FE',
    colors: {
      primary: '#150C22',
      secondary: '#584B66',
      border: '#EDE4F7',
      accent: '#4F46E5',
      accentHover: '#4338CA',
      orange: '#F43F5E',
      orangeLight: '#FB7185',
      purple: '#4F46E5',
      purpleLight: '#818CF8',
      gradientStart: '#4F46E5',
      gradientEnd: '#F43F5E',
      bg: '#FCF9FE',
      bgAlt: '#F6EFFD',
      dark: '#0F071A',
      darkCard: '#1C0F2F',
    },
  },
  {
    id: 'champagne-onyx',
    name: 'Champagne Onyx & Gold',
    styleType: 'gradient',
    category: 'Private Equity & Sovereign Wealth',
    badge: 'Champagne Onyx',
    primarySwatch: '#18181B',
    secondarySwatch: '#D4AF37',
    bgSwatch: '#FAFAFA',
    colors: {
      primary: '#0C0D11',
      secondary: '#4F5057',
      border: '#E4E4E7',
      accent: '#CA8A04',
      accentHover: '#A16207',
      orange: '#D4AF37',
      orangeLight: '#FDE68A',
      purple: '#27272A',
      purpleLight: '#52525B',
      gradientStart: '#18181B',
      gradientEnd: '#D4AF37',
      bg: '#FAFAFA',
      bgAlt: '#F4F4F5',
      dark: '#070709',
      darkCard: '#141417',
    },
  },
  {
    id: 'forest-citron',
    name: 'Forest Pine & Golden Citron',
    styleType: 'gradient',
    category: 'Eco-Tech & Clean Energy',
    badge: 'Forest Citron',
    primarySwatch: '#14532D',
    secondarySwatch: '#84CC16',
    bgSwatch: '#F7FAF8',
    colors: {
      primary: '#08170D',
      secondary: '#45574A',
      border: '#D9EBDC',
      accent: '#15803D',
      accentHover: '#166534',
      orange: '#84CC16',
      orangeLight: '#A3E635',
      purple: '#14532D',
      purpleLight: '#16A34A',
      gradientStart: '#14532D',
      gradientEnd: '#84CC16',
      bg: '#F7FAF8',
      bgAlt: '#ECF5EE',
      dark: '#051109',
      darkCard: '#0C2013',
    },
  },
  {
    id: 'electric-lilac',
    name: 'Electric Lilac & Neo Indigo',
    styleType: 'gradient',
    category: 'Modern Web3 & SaaS',
    badge: 'Lilac Gradient',
    primarySwatch: '#6366F1',
    secondarySwatch: '#A855F7',
    bgSwatch: '#F9F9FE',
    colors: {
      primary: '#100F26',
      secondary: '#4E4D69',
      border: '#E6E5FA',
      accent: '#6366F1',
      accentHover: '#4F46E5',
      orange: '#A855F7',
      orangeLight: '#C084FC',
      purple: '#6366F1',
      purpleLight: '#818CF8',
      gradientStart: '#6366F1',
      gradientEnd: '#A855F7',
      bg: '#F9F9FE',
      bgAlt: '#F0EFFD',
      dark: '#0A091C',
      darkCard: '#141333',
    },
  },
  {
    id: 'matcha-blossom',
    name: 'Japanese Matcha & Blossom',
    styleType: 'gradient',
    category: 'Zen Minimal & Wellness',
    badge: 'Matcha Blossom',
    primarySwatch: '#4D7C0F',
    secondarySwatch: '#FB7185',
    bgSwatch: '#F9FBF8',
    colors: {
      primary: '#12180C',
      secondary: '#535A4D',
      border: '#E5EDE0',
      accent: '#4D7C0F',
      accentHover: '#3F6212',
      orange: '#FB7185',
      orangeLight: '#FDA4AF',
      purple: '#4D7C0F',
      purpleLight: '#65A30D',
      gradientStart: '#4D7C0F',
      gradientEnd: '#FB7185',
      bg: '#F9FBF8',
      bgAlt: '#EFF5ED',
      dark: '#0C1207',
      darkCard: '#17210E',
    },
  },
];

export function applyTheme(_themeId?: string) {
  if (typeof document === 'undefined') return;
  try {
    localStorage.removeItem('himani_active_theme');
  } catch (e) {
    // ignore
  }
}

export function getSavedTheme(): string {
  return 'lavender-gold';
}

